//LOGICA DE PARA OS VALORES
var carsAndModels = {};
var arrayProblemas = {};

arrayProblemas['Fiat'] = {
	buzina : "0,50",
	cabo_do_velocimetro : "XXXX",
	chave_de_seta : "1,50",
	chave_de_seta_c_air_bag : "2,50",
	cilindro_de_ignicao : "1,50",
	distribuidor : "XXXX",
	farol : "1,00",
	interruptor_da_ventoinha_cebolao : "0,50",
	interruptor_de_farol : "0,50",
	interruptor_de_marcha_re : "0,50",
	interruptor_de_oleo_motor : "0,50",
	interruptor_de_temp_injecao : "0,50",
	interruptor_de_temp_painel : "0,50",
	interruptor_luz_de_freio : "0,50",
	lampada_de_direcao_seta : "0,50",
	lampada_de_farol : "0,50",
	lampada_de_freio : "0,50",
	lampada_de_lanterna : "0,50",
	lampada_de_re : "0,50",
	motor_do_limpador_de_para_brisa : "2,00",
	motor_do_limpador_do_vigia : "2,00",
	painel_de_instrumentos : "4,00",
	valvula_termostatica : "1,00",
	ventilador_do_radiador : "1,50",
	vidro_de_acionamento_eletrico : "1,50",
	arvore_flexivel_direcao_cair_bag : "3.00",
	arvore_flexivel_direcao_sair_bag : "2.00",
	barra_central_estabilizadora : "XXXX",
	braco_axial_direcao : "1.00",
	braco_pitman : "XXXX",
	bucha_da_barra_de_direcao : "XXXX",
	caixa_de_direcao_hidraulica : "5.00",
	caixa_de_direcao_hidraulica : "8.00",
	caixa_de_direcao_mecanica : "4.00",
	caixa_de_direcao_mecanica : "6.00",
	coifa_da_caixa_de_direcao : "1.00",
	coifa_de_homocinetica_externa : "XXXX",
	coifa_de_homocinetica_interna : "XXXX",
	coluna_de_direcao : "2.00",
	correia_da_direcao_hidraulica : "1.00",
	rolamento_de_roda_dianteira : "XXXX",
	rolamento_de_roda_traseira : "XXXX",
	terminal_de_direcao : "0.50",
	volante_da_direcao : "0.50",
	volante_da_direcao_s_airbag : "XXXX",
	cabo_de_embreagem : "1.00",
	embreagem_kit : "6.00",
	coletor_de_admissao : "2.00",
	coletor_de_escapamento : "2.00",
	escapamento_final : "1.00",
	escapamento_intermediario : "1.00",
	escapamento_primario : "2.00",
	junta_coletor_admissao : "8.00",
	junta_coletor_escapamento : "2.00",
	selo_d_agua_coletor_admissao : "3.00",
	cabo_do_freio_de_mao : "1.00",
	cano_de_freio_roda : "1.00",
	cilindro_mestre_do_freio : "2.00",
	cillindro_de_freio_da_roda_traseira : "1.00",
	corretor_de_frenagem_equalizadora : "1.00",
	flexivel_de_freio_mangote : "0.50",
	fluido_de_freio : "1.00",
	freios_4_rodas_c_lonas : "XXXX",
	freios_4_rodas_c_pincas : "6.00",
	freios_dianteiros : "1.50",
	freios_traseiros : "2.00",
	hidrovacuo_de_freio : "2.00",
	lona_de_freio_ : "1.00",
	pastilha_de_freio_jogo : "1.00",
	pinca_de_freio_reparo : "1.50",
	tambor_de_freio_dianteiro : "XXXX",
	tambor_de_freio_traseiro : "1.00",
	amortecedor_dianteiro : "1.00",
	amortecedor_traseiro : "1.00",
	bandeja_dianteira_inferior : "1.00",
	bandeja_dianteira_superior : "XXXX",
	bandeja_traseira : "XXXX",
	barra_central_estabilizadora : "XXXX",
	bieletas_liame : "1.00",
	braco_axial_direcao : "XXXX",
	braco_oscilante_suspensao_dianteira_inferior : "XXXX",
	braco_oscilante_suspensao_dianteira_superior : "XXXX",
	braco_pitman : "XXXX",
	braco_tensor_suspensao_dianteira : "1.00",
	braco_transversal_suspensao_traseira : "XXXX",
	bucha_bandeja_dianteira_inferior : "XXXX",
	bucha_bandeja_dianteira_superior : "XXXX",
	bucha_braco_oscilante_suspensao_dianteira : "XXXX",
	bucha_da_barra_de_direcao : "XXXX",
	bucha_do_agregado : "XXXX",
	bucha_do_eixo_traseiro : "3.00",
	coifa_de_homocinetica_externa : "1.00",
	coifa_de_homocinetica_interna : "1.50",
	estabilizador_dianteiro : "2.00",
	estabilizador_traseiro : "1.00",
	feixe_de_molas : "XXXX",
	homocinetica_externa : "1.00",
	homocinetica_interna : "1.50",
	manga_de_eixo_dianteiro_c_rolamento : "1.50",
	manga_de_eixo_traseiro : "1.50",
	mola_helicoidal_dianteira : "1.00",
	mola_helicoidal_traseira : "1.00",
	pivo : "1.00",
	rolamento_de_roda_dianteira : "1.50",
	rolamento_de_roda_traseira : "1.00",
	tensor_de_suspensao_dianteira : "XXXX",
	tensor_de_suspensao_traseira : "XXXX",
	terminal_de_direcao : "XXXX",
	torre_de_suspensao_dianteira : "1.00",
	torre_de_suspensao_traseira : "XXXX",
	travessa_eixo_traseiro : "XXXX",
	alavanca_de_marchas : "XXXX",
	alavanca_de_marchas : "XXXX",
	alavanca_superior : "XXXX",
	cambio_automatico : "XXXX",
	cambio_mecanico : "XXXX",
	carter_cambio_automatico : "XXXX",
	carter_motor : "XXXX",
	correia_dentada_distribuicao : "XXXX",
	coxim_do_cambio_central : "XXXX",
	coxim_do_cambio_LE : "XXXX",
	junta_do_carter_cambio_automatico : "XXXX",
	rolamento_semi_eixo_intermediario : "XXXX",
	semi_eixo : "XXXX",
	travessa_central_inferior_cambio : "XXXX",
	travessa_eixo_traseiro : "XXXX",
	alternador : "XXXX",
	alternador : "XXXX",
	correia_do : "XXXX"
};

arrayProblemas['Volkswagem'] = {
	buzina : "0,50",
	cabo_do_velocimetro : "1,00",
	chave_de_seta : "1,00",
	chave_de_seta_c_air_bag : "XXXX",
	cilindro_de_ignicao : "1,00",
	distribuidor : "1,00",
	farol : "0,50",
	interruptor_da_ventoinha_cebolao : "0,50",
	interruptor_de_farol : "0,50",
	interruptor_de_marcha_re : "0,50",
	interruptor_de_oleo_motor : "0,50",
	interruptor_de_temp_injecao : "0,50",
	interruptor_de_temp_painel : "0,50",
	interruptor_luz_de_freio : "0,50",
	lampada_de_direcao_seta : "0,50",
	lampada_de_farol : "0,50",
	lampada_de_freio : "0,50",
	lampada_de_lanterna : "0,50",
	lampada_de_re : "0,50",
	motor_do_limpador_de_para_brisa : "2,00",
	motor_do_limpador_do_vigia : "XXXX",
	painel_de_instrumentos : "XXXX",
	valvula_termostatica : "XXXX",
	ventilador_do_radiador : "XXXX",
	vidro_de_acionamento_eletrico : "XXXX",
	arvore_flexivel_direcao_cair_bag : "3.00",
	arvore_flexivel_direcao_sair_bag : "2.00",
	barra_central_estabilizadora : "XXXX",
	braco_axial_direcao : "XXXX",
	braco_pitman : "XXXX",
	bucha_da_barra_de_direcao : "1.00",
	caixa_de_direcao_hidraulica : "3.00",
	caixa_de_direcao_hidraulica : "6.00",
	caixa_de_direcao_mecanica : "3.00",
	caixa_de_direcao_mecanica : "2.00",
	coifa_da_caixa_de_direcao : "1.00",
	coifa_de_homocinetica_externa : "XXXX",
	coifa_de_homocinetica_interna : "XXXX",
	coluna_de_direcao : "2.00",
	correia_da_direcao_hidraulica : "0.50",
	rolamento_de_roda_dianteira : "XXXX",
	rolamento_de_roda_traseira : "XXXX",
	terminal_de_direcao : "0.50",
	volante_da_direcao : "0.50",
	volante_da_direcao_s_airbag : "XXXX",
	cabo_de_embreagem : "1.00",
	embreagem_kit : "4.00",
	coletor_de_admissao : "XXXX",
	coletor_de_escapamento : "4.00",
	escapamento_final : "1.00",
	escapamento_intermediario : "1.00",
	escapamento_primario : "1.00",
	junta_coletor_admissao : "2.00",
	junta_coletor_escapamento : "4.00",
	selo_d_agua_coletor_admissao : "1.00",
	cabo_do_freio_de_mao : "1.00",
	cano_de_freio_roda : "0.50",
	cilindro_mestre_do_freio : "2.00",
	cillindro_de_freio_da_roda_traseira : "1.00",
	corretor_de_frenagem_equalizadora : "0.50",
	flexivel_de_freio_mangote : "0.50",
	fluido_de_freio : "1.00",
	freios_4_rodas_c_lonas : "4.00",
	freios_4_rodas_c_pincas : "3.50",
	freios_dianteiros : "1.50",
	freios_traseiros : "2.00",
	hidrovacuo_de_freio : "2.00",
	lona_de_freio_ : "2.00",
	pastilha_de_freio_jogo : "1.00",
	pinca_de_freio_reparo : "1.00",
	tambor_de_freio_dianteiro : "XXXX",
	tambor_de_freio_traseiro : "1.00",
	amortecedor_dianteiro : "1.00",
	amortecedor_traseiro : "1.00",
	bandeja_dianteira_inferior : "1.00",
	bandeja_dianteira_superior : "XXXX",
	bandeja_traseira : "XXXX",
	barra_central_estabilizadora : "XXXX",
	bieletas_liame : "XXXX",
	braco_axial_direcao : "XXXX",
	braco_oscilante_suspensao_dianteira_inferior : "XXXX",
	braco_oscilante_suspensao_dianteira_superior : "XXXX",
	braco_pitman : "XXXX",
	braco_tensor_suspensao_dianteira : "XXXX",
	braco_transversal_suspensao_traseira : "XXXX",
	bucha_bandeja_dianteira_inferior : "1.00",
	bucha_bandeja_dianteira_superior : "XXXX",
	bucha_braco_oscilante_suspensao_dianteira : "XXXX",
	bucha_da_barra_de_direcao : "XXXX",
	bucha_do_agregado : "3.00",
	bucha_do_eixo_traseiro : "2.00",
	coifa_de_homocinetica_externa : "1.00",
	coifa_de_homocinetica_interna : "1.50",
	estabilizador_dianteiro : "1.00",
	estabilizador_traseiro : "XXXX",
	feixe_de_molas : "XXXX",
	homocinetica_externa : "1.00",
	homocinetica_interna : "1.50",
	manga_de_eixo_dianteiro_c_rolamento : "1.00",
	manga_de_eixo_traseiro : "1.00",
	mola_helicoidal_dianteira : "1.00",
	mola_helicoidal_traseira : "1.00",
	pivo : "0.50",
	rolamento_de_roda_dianteira : "1.00",
	rolamento_de_roda_traseira : "1.00",
	tensor_de_suspensao_dianteira : "1.00",
	tensor_de_suspensao_traseira : "XXXX",
	terminal_de_direcao : "XXXX",
	torre_de_suspensao_dianteira : "1.00",
	torre_de_suspensao_traseira : "XXXX",
	travessa_eixo_traseiro : "XXXX",
	alavanca_de_marchas : "XXXX",
	alavanca_de_marchas : "XXXX",
	alavanca_superior : "XXXX",
	cambio_automatico : "XXXX",
	cambio_mecanico : "XXXX",
	carter_cambio_automatico : "XXXX",
	carter_motor : "XXXX",
	correia_dentada_distribuicao : "XXXX",
	coxim_do_cambio_central : "XXXX",
	coxim_do_cambio_LE : "XXXX",
	junta_do_carter_cambio_automatico : "XXXX",
	rolamento_semi_eixo_intermediario : "XXXX",
	semi_eixo : "XXXX",
	travessa_central_inferior_cambio : "XXXX",
	travessa_eixo_traseiro : "XXXX",
	alternador : "XXXX",
	alternador : "XXXX",
	correia_do : "XXXX"
};

arrayProblemas['Chevrolet'] = {
	buzina : "0,50",
	cabo_do_velocimetro : "1,00",
	chave_de_seta : "1,00",
	chave_de_seta_c_air_bag : "2,00",
	cilindro_de_ignicao : "1,00",
	distribuidor : "XXXX",
	farol : "0,50",
	interruptor_da_ventoinha_cebolao : "0,50",
	interruptor_de_farol : "0,50",
	interruptor_de_marcha_re : "0,50",
	interruptor_de_oleo_motor : "0,50",
	interruptor_de_temp_injecao : "0,50",
	interruptor_de_temp_painel : "0,50",
	interruptor_luz_de_freio : "0,50",
	lampada_de_direcao_seta : "0,50",
	lampada_de_farol : "0,50",
	lampada_de_freio : "0,50",
	lampada_de_lanterna : "0,50",
	lampada_de_re : "0,50",
	motor_do_limpador_de_para_brisa : "1,00",
	motor_do_limpador_do_vigia : "1,00",
	painel_de_instrumentos : "2,00",
	valvula_termostatica : "1,00",
	ventilador_do_radiador : "1,50",
	vidro_de_acionamento_eletrico : "1,00",
	arvore_flexivel_direcao_cair_bag : "2.00",
	arvore_flexivel_direcao_sair_bag : "3.00",
	barra_central_estabilizadora : "1.00",
	braco_axial_direcao : "XXXX",
	braco_pitman : "XXXX",
	bucha_da_barra_de_direcao : "XXXX",
	caixa_de_direcao_hidraulica : "4.00",
	caixa_de_direcao_hidraulica : "5.00",
	caixa_de_direcao_mecanica : "4.00",
	caixa_de_direcao_mecanica : "3.00",
	coifa_da_caixa_de_direcao : "XXXX",
	coifa_de_homocinetica_externa : "XXXX",
	coifa_de_homocinetica_interna : "XXXX",
	coluna_de_direcao : "2.00",
	correia_da_direcao_hidraulica : "1.00",
	rolamento_de_roda_dianteira : "XXXX",
	rolamento_de_roda_traseira : "XXXX",
	terminal_de_direcao : "0.50",
	volante_da_direcao : "XXXX",
	volante_da_direcao_s_airbag : "XXXX",
	cabo_de_embreagem : "1.00",
	embreagem_kit : "8.00",
	coletor_de_admissao : "2.00",
	coletor_de_escapamento : "2.00",
	escapamento_final : "1.00",
	escapamento_intermediario : "1.00",
	escapamento_primario : "1.00",
	junta_coletor_admissao : "2.00",
	junta_coletor_escapamento : "2.00",
	selo_d_agua_coletor_admissao : "1.50",
	cabo_do_freio_de_mao : "1.00",
	cano_de_freio_roda : "1.00",
	cilindro_mestre_do_freio : "2.00",
	cillindro_de_freio_da_roda_traseira : "1.00",
	corretor_de_frenagem_equalizadora : "1.00",
	flexivel_de_freio_mangote : "0.50",
	fluido_de_freio : "XXXX",
	freios_4_rodas_c_lonas : "5.00",
	freios_4_rodas_c_pincas : "4.00",
	freios_dianteiros : "1.50",
	freios_traseiros : "2.00",
	hidrovacuo_de_freio : "2.00",
	lona_de_freio_ : "1.00",
	pastilha_de_freio_jogo : "1.00",
	pinca_de_freio_reparo : "1.00",
	tambor_de_freio_dianteiro : "XXXX",
	tambor_de_freio_traseiro : "1.00",
	amortecedor_dianteiro : "1.00",
	amortecedor_traseiro : "0.50",
	bandeja_dianteira_inferior : "1.00",
	bandeja_dianteira_superior : "2.00",
	bandeja_traseira : "XXXX",
	barra_central_estabilizadora : "XXXX",
	bieletas_liame : "0.50",
	braco_axial_direcao : "XXXX",
	braco_oscilante_suspensao_dianteira_inferior : "2.00",
	braco_oscilante_suspensao_dianteira_superior : "XXXX",
	braco_pitman : "1.00",
	braco_tensor_suspensao_dianteira : "XXXX",
	braco_transversal_suspensao_traseira : "XXXX",
	bucha_bandeja_dianteira_inferior : "2.00",
	bucha_bandeja_dianteira_superior : "XXXX",
	bucha_braco_oscilante_suspensao_dianteira : "XXXX",
	bucha_da_barra_de_direcao : "XXXX",
	bucha_do_agregado : "XXXX",
	bucha_do_eixo_traseiro : "XXXX",
	coifa_de_homocinetica_externa : "XXXX",
	coifa_de_homocinetica_interna : "XXXX",
	estabilizador_dianteiro : "1.00",
	estabilizador_traseiro : "XXXX",
	feixe_de_molas : "XXXX",
	homocinetica_externa : "XXXX",
	homocinetica_interna : "XXXX",
	manga_de_eixo_dianteiro_c_rolamento : "2.50",
	manga_de_eixo_traseiro : "XXXX",
	mola_helicoidal_dianteira : "1.00",
	mola_helicoidal_traseira : "XXXX",
	pivo : "1.00",
	rolamento_de_roda_dianteira : "2.00",
	rolamento_de_roda_traseira : "3.00",
	tensor_de_suspensao_dianteira : "XXXX",
	tensor_de_suspensao_traseira : "XXXX",
	terminal_de_direcao : "XXXX",
	torre_de_suspensao_dianteira : "1.50",
	torre_de_suspensao_traseira : "XXXX",
	travessa_eixo_traseiro : "XXXX",
	alavanca_de_marchas : "1.50 ",
	alavanca_de_marchas : "XXXX ",
	alavanca_superior : "XXXX ",
	cambio_automatico : "36.00",
	cambio_mecanico : "15.00",
	carter_cambio_automatico : "4.00 ",
	carter_motor : "XXXX ",
	correia_dentada_distribuicao : "XXXX ",
	coxim_do_cambio_central : "2.00 ",
	coxim_do_cambio_LE : "1.00 ",
	junta_do_carter_cambio_automatico : "1.00 ",
	rolamento_semi_eixo_intermediario : "3.00 ",
	semi_eixo : "XXXX ",
	travessa_central_inferior_cambio : "1.00 ",
	travessa_eixo_traseiro : "XXXX ",
	alternador : "",
	alternador : "",
	correia_do : ""
};

arrayProblemas['Ford'] = {
	buzina : "0,50",
	cabo_do_velocimetro : "1,00",
	chave_de_seta : "1,50",
	chave_de_seta_c_air_bag : "2,00",
	cilindro_de_ignicao : "1,00",
	distribuidor : "3,00",
	farol : "1,00",
	interruptor_da_ventoinha_cebolao : "1,00",
	interruptor_de_farol : "1,00",
	interruptor_de_marcha_re : "0,50",
	interruptor_de_oleo_motor : "0,50",
	interruptor_de_temp_injecao : "0,50",
	interruptor_de_temp_painel : "0,50",
	interruptor_luz_de_freio : "0,50",
	lampada_de_direcao_seta : "0,50",
	lampada_de_farol : "0,50",
	lampada_de_freio : "0,50",
	lampada_de_lanterna : "0,50",
	lampada_de_re : "0,50",
	motor_do_limpador_de_para_brisa : "2,00",
	motor_do_limpador_do_vigia : "1,00",
	painel_de_instrumentos : "3,00",
	valvula_termostatica : "2,00",
	ventilador_do_radiador : "3,00",
	vidro_de_acionamento_eletrico : "2,00",
	arvore_flexivel_direcao_cair_bag : "3.00",
	arvore_flexivel_direcao_sair_bag : "2.00",
	barra_central_estabilizadora : "XXXX",
	braco_axial_direcao : "1.00",
	braco_pitman : "XXXX",
	bucha_da_barra_de_direcao : "XXXX",
	caixa_de_direcao_hidraulica : "3.00",
	caixa_de_direcao_hidraulica : "6.00",
	caixa_de_direcao_mecanica : "3.00",
	caixa_de_direcao_mecanica : "4.00",
	coifa_da_caixa_de_direcao : "1.00",
	coifa_de_homocinetica_externa : "XXXX",
	coifa_de_homocinetica_interna : "XXXX",
	coluna_de_direcao : "2.00",
	correia_da_direcao_hidraulica : "1.00",
	rolamento_de_roda_dianteira : "XXXX",
	rolamento_de_roda_traseira : "XXXX",
	terminal_de_direcao : "0.50",
	volante_da_direcao : "XXXX",
	volante_da_direcao_s_airbag : "0.50",
	cabo_de_embreagem : "1.00",
	embreagem_kit : "6.00",
	coletor_de_admissao : "3.00",
	coletor_de_escapamento : "3.00",
	escapamento_final : "1.00",
	escapamento_intermediario : "1.00",
	escapamento_primario : "1.00",
	junta_coletor_admissao : "3.00",
	junta_coletor_escapamento : "3.00",
	selo_d_agua_coletor_admissao : "3.00",
	cabo_do_freio_de_mao : "2.00",
	cano_de_freio_roda : "0.50",
	cilindro_mestre_do_freio : "1.50",
	cillindro_de_freio_da_roda_traseira : "1.00",
	corretor_de_frenagem_equalizadora : "1.00",
	flexivel_de_freio_mangote : "1.00",
	fluido_de_freio : "1.00",
	freios_4_rodas_c_lonas : "5.00",
	freios_4_rodas_c_pincas : "4.00",
	freios_dianteiros : "1.00",
	freios_traseiros : "2.00",
	hidrovacuo_de_freio : "1.50",
	lona_de_freio_ : "2.00",
	pastilha_de_freio_jogo : "1.00",
	pinca_de_freio_reparo : "1.00",
	tambor_de_freio_dianteiro : "XXXX",
	tambor_de_freio_traseiro : "1.00",
	amortecedor_dianteiro : "1.00",
	amortecedor_traseiro : "1.00",
	bandeja_dianteira_inferior : "XXXX",
	bandeja_dianteira_superior : "XXXX",
	bandeja_traseira : "1.50",
	barra_central_estabilizadora : "XXXX",
	bieletas_liame : "0.50",
	braco_axial_direcao : "XXXX",
	braco_oscilante_suspensao_dianteira_inferior : "1.00",
	braco_oscilante_suspensao_dianteira_superior : "1.50",
	braco_pitman : "XXXX",
	braco_tensor_suspensao_dianteira : "XXXX",
	braco_transversal_suspensao_traseira : "XXXX",
	bucha_bandeja_dianteira_inferior : "1.50",
	bucha_bandeja_dianteira_superior : "XXXX",
	bucha_braco_oscilante_suspensao_dianteira : "XXXX",
	bucha_da_barra_de_direcao : "1.00",
	bucha_do_agregado : "XXXX",
	bucha_do_eixo_traseiro : "2.00",
	coifa_de_homocinetica_externa : "1.00",
	coifa_de_homocinetica_interna : "1.50",
	estabilizador_dianteiro : "1.00",
	estabilizador_traseiro : "XXXX",
	feixe_de_molas : "XXXX",
	homocinetica_externa : "1.00",
	homocinetica_interna : "1.50",
	manga_de_eixo_dianteiro_c_rolamento : "1.50",
	manga_de_eixo_traseiro : "1.00",
	mola_helicoidal_dianteira : "1.00",
	mola_helicoidal_traseira : "1.00",
	pivo : "1.00",
	rolamento_de_roda_dianteira : "1.50",
	rolamento_de_roda_traseira : "1.00",
	tensor_de_suspensao_dianteira : "XXXX",
	tensor_de_suspensao_traseira : "XXXX",
	terminal_de_direcao : "XXXX",
	torre_de_suspensao_dianteira : "1.50",
	torre_de_suspensao_traseira : "1.50",
	travessa_eixo_traseiro : "1.50",
	alavanca_de_marchas : "3.00 ",
	alavanca_de_marchas : "XXXX ",
	alavanca_superior : "XXXX ",
	cambio_automatico : "26.00",
	cambio_mecanico : "10.00",
	carter_cambio_automatico : "1.50 ",
	carter_motor : "XXXX ",
	correia_dentada_distribuicao : "XXXX ",
	coxim_do_cambio_central : "1.00 ",
	coxim_do_cambio_LE : "1.00 ",
	junta_do_carter_cambio_automatico : "XXXX ",
	rolamento_semi_eixo_intermediario : "XXXX ",
	semi_eixo : "1.50 ",
	travessa_central_inferior_cambio : "1.00 ",
	travessa_eixo_traseiro : "XXXX ",
	alternador : "",
	alternador : "",
	correia_do : ""
};

arrayProblemas['Peugeot'] = {
	buzina : "0,50",
	cabo_do_velocimetro : "1,00",
	chave_de_seta : "1,00",
	chave_de_seta_c_air_bag : "2,50",
	cilindro_de_ignicao : "1,50",
	distribuidor : "XXXX",
	farol : "0,50",
	interruptor_da_ventoinha_cebolao : "1,00",
	interruptor_de_farol : "0,50",
	interruptor_de_marcha_re : "0,50",
	interruptor_de_oleo_motor : "0,50",
	interruptor_de_temp_injecao : "0,50",
	interruptor_de_temp_painel : "0,50",
	interruptor_luz_de_freio : "0,50",
	lampada_de_direcao_seta : "0,50",
	lampada_de_farol : "0,50",
	lampada_de_freio : "0,50",
	lampada_de_lanterna : "0,50",
	lampada_de_re : "0,50",
	motor_do_limpador_de_para_brisa : "1,00",
	motor_do_limpador_do_vigia : "1,00",
	painel_de_instrumentos : "3,00",
	valvula_termostatica : "1,00",
	ventilador_do_radiador : "1,00",
	vidro_de_acionamento_eletrico : "1,50",
	arvore_flexivel_direcao_cair_bag : "3.00",
	arvore_flexivel_direcao_sair_bag : "2.00",
	barra_central_estabilizadora : "XXXX",
	braco_axial_direcao : "1.00",
	braco_pitman : "XXXX",
	bucha_da_barra_de_direcao : "1.00",
	caixa_de_direcao_hidraulica : "3.00",
	caixa_de_direcao_hidraulica : "6.00",
	caixa_de_direcao_mecanica : "2.00",
	caixa_de_direcao_mecanica : "4.00",
	coifa_da_caixa_de_direcao : "1.50",
	coifa_de_homocinetica_externa : "XXXX",
	coifa_de_homocinetica_interna : "XXXX",
	coluna_de_direcao : "2.00",
	correia_da_direcao_hidraulica : "0.50",
	rolamento_de_roda_dianteira : "XXXX",
	rolamento_de_roda_traseira : "XXXX",
	terminal_de_direcao : "0.50",
	volante_da_direcao : "0.20",
	volante_da_direcao_s_airbag : "XXXX",
	cabo_de_embreagem : "1.00",
	embreagem_kit : "5.00",
	coletor_de_admissao : "5.00",
	coletor_de_escapamento : "1.00",
	escapamento_final : "1.00",
	escapamento_intermediario : "1.00",
	escapamento_primario : "1.00",
	junta_coletor_admissao : "2.00",
	junta_coletor_escapamento : "1.00",
	selo_d_agua_coletor_admissao : "1.00",
	cabo_do_freio_de_mao : "1.00",
	cano_de_freio_roda : "1.00",
	cilindro_mestre_do_freio : "1.00",
	cillindro_de_freio_da_roda_traseira : "1.00",
	corretor_de_frenagem_equalizadora : "0.50",
	flexivel_de_freio_mangote : "1.00",
	fluido_de_freio : "1.00",
	freios_4_rodas_c_lonas : "4.00",
	freios_4_rodas_c_pincas : "5.00",
	freios_dianteiros : "1.00",
	freios_traseiros : "2.00",
	hidrovacuo_de_freio : "1.50",
	lona_de_freio_ : "2.00",
	pastilha_de_freio_jogo : "1.00",
	pinca_de_freio_reparo : "1.00",
	tambor_de_freio_dianteiro : "XXXX",
	tambor_de_freio_traseiro : "1.00",
	amortecedor_dianteiro : "1.50",
	amortecedor_traseiro : "1.00",
	bandeja_dianteira_inferior : "1.00",
	bandeja_dianteira_superior : "1.00",
	bandeja_traseira : "1.00",
	barra_central_estabilizadora : "XXXX",
	bieletas_liame : "0.50",
	braco_axial_direcao : "XXXX",
	braco_oscilante_suspensao_dianteira_inferior : "1.50",
	braco_oscilante_suspensao_dianteira_superior : "XXXX",
	braco_pitman : "XXXX",
	braco_tensor_suspensao_dianteira : "1.00",
	braco_transversal_suspensao_traseira : "1.00",
	bucha_bandeja_dianteira_inferior : "1.50",
	bucha_bandeja_dianteira_superior : "XXXX",
	bucha_braco_oscilante_suspensao_dianteira : "XXXX",
	bucha_da_barra_de_direcao : "1.00",
	bucha_do_agregado : "XXXX",
	bucha_do_eixo_traseiro : "3.00",
	coifa_de_homocinetica_externa : "1.00",
	coifa_de_homocinetica_interna : "2.00",
	estabilizador_dianteiro : "1.50",
	estabilizador_traseiro : "1.50",
	feixe_de_molas : "XXXX",
	homocinetica_externa : "1.00",
	homocinetica_interna : "1.50",
	manga_de_eixo_dianteiro_c_rolamento : "1.50",
	manga_de_eixo_traseiro : "1.50",
	mola_helicoidal_dianteira : "2.00",
	mola_helicoidal_traseira : "2.00",
	pivo : "1.00",
	rolamento_de_roda_dianteira : "1.00",
	rolamento_de_roda_traseira : "1.00",
	tensor_de_suspensao_dianteira : "2.50",
	tensor_de_suspensao_traseira : "1.00",
	terminal_de_direcao : "XXXX",
	torre_de_suspensao_dianteira : "1.50",
	torre_de_suspensao_traseira : "1.50",
	travessa_eixo_traseiro : "XXXX",
	alavanca_de_marchas : "1.50 ",
	alavanca_de_marchas : "XXXX ",
	alavanca_superior : "XXXX ",
	cambio_automatico : "26.00",
	cambio_mecanico : "15.00",
	carter_cambio_automatico : "1.50 ",
	carter_motor : "XXXX ",
	correia_dentada_distribuicao : "XXXX ",
	coxim_do_cambio_central : "1.00 ",
	coxim_do_cambio_LE : "1.00 ",
	junta_do_carter_cambio_automatico : "XXXX ",
	rolamento_semi_eixo_intermediario : "1.50 ",
	semi_eixo : "1.00 ",
	travessa_central_inferior_cambio : "1.00 ",
	travessa_eixo_traseiro : "1.00 ",
	alternador : "",
	alternador : "",
	correia_do : ""
};

// FIAT
carsAndModels['Fiat'] = [ 'N\u00e3o Sei', 'MAREA', 'PALIO 16V', 'PALIO 8V',
		'TEMPRA', 'TIPO ', 'UNO /93', 'UNO 94/' ];

// VOLKS
carsAndModels['Volkswagem'] = [ 'N\u00e3o sei', 'Á AR', 'APOLO', 'BORA', 'FOX',
		'GOL /95', 'GOL /96', 'GOL /97', 'GOL GIII', 'GOLF', 'KOMBI', 'LOGUS',
		'PASSAT', 'PASSAT', 'PASSAT', 'PASSAT', 'SANTANA', 'SANTANA /97', 'VAN' ];

carsAndModels['Chevrolet'] = [ 'N\u00e3o Sei', 'BLAZER', 'CALIBRA', 'CELTA',
		'CHEV', 'CORSA 8V', 'CORSA 16V', 'MONZA ', 'OMEGA /96', 'OPALA',
		'SILVERADO', 'TIGRA', 'VECTRA', 'ZAFIRA' ];

// FORD
carsAndModels['Ford'] = [ 'N\u00e3o sei', 'CORCEL', 'DELREY', 'ESCORT',
		'FIESTA', 'FOCUS', 'KA', 'MONDEO', 'MUSTANG', 'TAURUS', 'VERSALLES' ];

// VAR PEUGEOT
carsAndModels['Peugeot'] = [ 'N\u00e3o sei', '106', '205', '206', '206', '206',
		'306', '405', '406', '504', 'BOXER', 'PARTNER' ];

/* CITROEN
 carsAndModels['Citroen']= [ 'N&atilde;o sei','AirCross','AX','Berlingo','C3',
 'C3 Picasso','C4 Grand Picasso','C4 Hatch','C4 Pallas',
 'C4 Picasso','C4 VTR','C5','C6','C8','DS3','Evasion',
 'Jumper','Xantia','XM','Xsara','Xsara Picasso','ZX' ];


 // HONDA
 carsAndModels['Honda'] = [ 'N&atilde;o sei','Accord','City','Civic','CR-V','Fit',
 'Legend','Odyssey','Passport','Pilot','Prelude' ];


 carsAndModels['Renault'] = [ 'N&atilde;o sei', '19', '21 Nevada', '21 Sedan', 'Clio', 'Duster',
 'Express', 'Fluence', 'Grand Scénic', 'Kangoo', 'Laguna', 'Logan',
 'Master', 'Mégane', 'Mégane Scénic', 'Sandero', 'Symbol', 'Trafic',
 'Twingo' ]; */

function clearSelectOptions() {

}

function gerarValorHora(problema, montadora) {

	if (montadora != "nao_sei") {
		if (problema != "selecione_o_problema" && problema != "nao_sei") {

			var arrayHoraProblema = arrayProblemas[montadora];
			var valorMaoDeObra = 60;

			var compare = arrayHoraProblema[problema];
			compare.localeCompare("XXXX");

			if (compare.localeCompare("XXXX") != 0) {
				var horaProblema = Math
						.ceil(parseFloat(arrayHoraProblema[problema]));
				if (horaProblema == 0) {
					horaProblema = 1;
				}
				document.getElementById('valor').innerHTML = "<h4 class='thin' style='font-weight: bold; color: #019AA2'> Valor  m&atilde;o de obra: R$"
						+ (valorMaoDeObra * horaProblema)
						+ ",00"
						+ "</h4>";

			} else {
				document.getElementById('valor').innerHTML = "<h4 class='thin' style='font-weight: bold; color: #019AA2'> Valor  m&atilde;o de obra n&atilde;o encontrado para este servi&ccedil;o </H4>";
			}

		} else {
			document.getElementById('valor').innerHTML = "<h4 class='thin' style='font-weight: bold; color: #019AA2'> Valor  m&atilde;o de obra n&atilde;o encontrado para este servi&ccedil;o </H4>";

		}
	}
}

function calcularHora() {

	var option_problem = document.getElementById("select_problema");
	var option_montadora = document.getElementById("car");
	var option_modelo = document.getElementById("carmodel");
	var option_ano = document.getElementById("ano");
	var option_hora = "";

	var car = {};
	car['problema'] = option_problem.options[option_problem.selectedIndex].value;
	car['montadora'] = option_montadora.options[option_montadora.selectedIndex].value;
	car['modelo'] = option_modelo.options[option_modelo.selectedIndex].value;
	car['hora'] = option_hora;

	gerarValorHora(car.problema, car.montadora);

	return true;
}

function ChangeCarList() {

	var option_problem = document.getElementById("select_problema");
	var option_montadora = document.getElementById("car");
	var option_modelo = document.getElementById("carmodel");
	var option_ano = document.getElementById("ano");
	var option_hora = "";

	//var car = {};
	var carList = document.getElementById("car");
	var modelList = document.getElementById("carmodel");
	var selCar = carList.options[carList.selectedIndex].value;
	var problem = document.getElementById("select_problema");
	problem.options[problem.selectedIndex].value;

	while (modelList.options.length) {
		modelList.remove(0);
	}

	var cars = carsAndModels[selCar];

	if (cars) {
		for (var i = 0; i < cars.length; i++) {
			var car = new Option(cars[i], cars[i]);
			modelList.options.add(car);
		}
	}
}
